# Generated by Django 4.2.7 on 2025-07-15 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoruntüAnaliz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorev_id', models.CharField(max_length=50, unique=True, verbose_name='Görev ID')),
                ('koordinat_enlem', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Enlem')),
                ('koordinat_boylam', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Boylam')),
                ('yukseklik', models.FloatField(verbose_name='Yükseklik (m)')),
                ('cekim_zamani', models.DateTimeField(verbose_name='Çekim Zamanı')),
                ('olusturma_zamani', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Zamanı')),
                ('guncelleme_zamani', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Zamanı')),
                ('foto_sag', models.ImageField(upload_to='fotograflar/sag/%Y/%m/', verbose_name='Sağ Fotoğraf')),
                ('foto_sol', models.ImageField(upload_to='fotograflar/sol/%Y/%m/', verbose_name='Sol Fotoğraf')),
                ('foto_on', models.ImageField(upload_to='fotograflar/on/%Y/%m/', verbose_name='Ön Fotoğraf')),
                ('foto_arka', models.ImageField(upload_to='fotograflar/arka/%Y/%m/', verbose_name='Arka Fotoğraf')),
                ('foto_ust', models.ImageField(upload_to='fotograflar/ust/%Y/%m/', verbose_name='Üst Fotoğraf')),
                ('analiz_durumu', models.CharField(choices=[('beklemede', 'Beklemede'), ('isleniyor', 'İşleniyor'), ('tamamlandi', 'Tamamlandı'), ('hatali', 'Hatalı')], default='beklemede', max_length=20, verbose_name='Analiz Durumu')),
                ('tespit_sonucu', models.CharField(blank=True, choices=[('saglam', 'Sağlam'), ('hasarli', 'Hasarlı'), ('degismeli', 'Değişmeli'), ('belirsiz', 'Belirsiz')], max_length=30, null=True, verbose_name='Tespit Sonucu')),
                ('guven_skoru', models.FloatField(blank=True, help_text='0-100 arası değer', null=True, verbose_name='Güven Skoru (%)')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operatör')),
            ],
            options={
                'verbose_name': 'Görüntü Analiz',
                'verbose_name_plural': 'Görüntü Analizleri',
                'ordering': ['-olusturma_zamani'],
            },
        ),
        migrations.CreateModel(
            name='AnalizeGecmisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem', models.CharField(max_length=100, verbose_name='İşlem')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('islem_zamani', models.DateTimeField(auto_now_add=True, verbose_name='İşlem Zamanı')),
                ('goruntu_analiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analiz_gecmisi', to='goruntu_analiz.goruntüanaliz')),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analiz Geçmişi',
                'verbose_name_plural': 'Analiz Geçmişleri',
                'ordering': ['-islem_zamani'],
            },
        ),
        migrations.CreateModel(
            name='TespitDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_yon', models.CharField(choices=[('sag', 'Sağ'), ('sol', 'Sol'), ('on', 'Ön'), ('arka', 'Arka'), ('ust', 'Üst')], max_length=10, verbose_name='Fotoğraf Yönü')),
                ('nesne_tespit_edildi', models.BooleanField(default=False, verbose_name='Nesne Tespit Edildi')),
                ('hasar_tespit_edildi', models.BooleanField(default=False, verbose_name='Hasar Tespit Edildi')),
                ('tespit_skoru', models.FloatField(blank=True, null=True, verbose_name='Tespit Skoru')),
                ('x_koordinat', models.IntegerField(blank=True, null=True, verbose_name='X Koordinatı')),
                ('y_koordinat', models.IntegerField(blank=True, null=True, verbose_name='Y Koordinatı')),
                ('genislik', models.IntegerField(blank=True, null=True, verbose_name='Genişlik')),
                ('yukseklik_pixel', models.IntegerField(blank=True, null=True, verbose_name='Yükseklik (pixel)')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('olusturma_zamani', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Zamanı')),
                ('goruntu_analiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tespit_detaylari', to='goruntu_analiz.goruntüanaliz')),
            ],
            options={
                'verbose_name': 'Tespit Detayı',
                'verbose_name_plural': 'Tespit Detayları',
                'unique_together': {('goruntu_analiz', 'foto_yon')},
            },
        ),
    ]
